feat(actions/lint): Check packages

diff --git a/actions/lint/action.yml b/actions/lint/action.yml
--- a/actions/lint/action.yml
+++ b/actions/lint/action.yml
@@ -15,6 +15,10 @@ inputs:
     description: |-
       Check sources with ESLint.
     default: 'false'
+  packages:
+    description: |-
+      Check packages are sorted and well-formed.
+    default: 'false'
   prettier:
     description: |-
       Check sources with Prettier.
@@ -62,4 +66,26 @@ runs:
             echo "::error::Beachball changes detected. Run 'pnpm beachball change' and commit the changes.";
             exit 1
           )
+        fi
+
+    - name: Packages
+      shell: bash
+      if: fromJson(inputs.packages)
+      run: |
+        pnpx sort-package-json --check \
+          ./apps/*/package.json \
+          ./packages/*/package.json \
+          package.json
+
+    - name: Check packages
+      shell: bash
+      if: fromJson(inputs.packages) && !fromJson(inputs.apply)
+      run: |
+        pnpm -r exec npm pkg fix
+
+        if [[ $(git status --porcelain) ]]; then
+          echo '::error::Some packages need fixing.'
+          git status
+          git diff
+          exit 1
         fi
